# Generated by Django 4.2.4 on 2023-09-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_email'),
        ('users', '0009_alter_passwordresetcode_code'),
    ]

    operations = [
    ]
