# Generated by Django 4.2.4 on 2023-09-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_passwordrcovery_delete_passwordresetcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordRcovery',
            new_name='PasswordRecovery',
        ),
    ]
