version: "3.9"

services:

  kt-guru:
    build:
      context: .
    ports:
      - 8000:8000

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ktbackend-db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}

volumes:
  ktbackend-db:


  # sqlitebrowser:
  #   image: lscr.io/linuxserver/sqlitebrowser:latest
  #   container_name: sqlitebrowser
  #   security_opt:
  #     - seccomp:unconfined 
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /path/to/config:/config
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #   restart: unless-stopped


  # front:
  #   # api:
  #   build:
  #     context: .
  #     target: development
  #   volumes:
  #     - .:/code1/
  #   ports:
  #     - 5174:8000
  #   command: npm run dev  

  # service:
  #   #api:
  #   build:
  #     context: . 
  #     target: production
    
  #   ports: 
  #     - 5174:8000
    

  # nginx:
  #   build:
  #     context: ./nginx/
  #   ports:
  #     - 8080:8080
