# Generated by Django 4.2.4 on 2023-09-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
                ('image_name', models.ImageField(default='static/recipes/no_recipe.jpg', upload_to='static/recipes')),
            ],
        ),
    ]
