# Generated by Django 4.2.5 on 2023-09-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_added',
            field=models.DateTimeField(null=True),
        ),
    ]
