# Generated by Django 4.2.4 on 2023-09-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_review_review_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='image_name',
        ),
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default='static/recipes/no_recipe.jpg', upload_to='KitchenGuru/static/recipes'),
        ),
        migrations.CreateModel(
            name='RecipesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='KitchenGuru/static/recipes')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
            ],
        ),
    ]
