# Generated by Django 4.2.5 on 2023-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_review_text_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Created at:'),
        ),
    ]
