# Generated by Django 4.2.5 on 2023-09-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at:'),
        ),
    ]
