# Generated by Django 4.2.4 on 2023-09-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipesimages_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesimages',
            name='image',
        ),
    ]
