# Generated by Django 4.2.4 on 2023-09-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipesimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='image',
        ),
        migrations.AddField(
            model_name='recipesimages',
            name='image',
            field=models.ImageField(default='static/recipes/no_recipe.jpg', upload_to='KitchenGuru/static/recipes'),
        ),
    ]
