# Generated by Django 4.2.4 on 2023-10-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipes_image_recipesimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesimages',
            name='image',
            field=models.ImageField(default='static/recipes/no_recipe.jpg', upload_to='recipes/'),
        ),
    ]
