# Generated by Django 4.2.4 on 2023-10-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipesimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='category',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredient_tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
