# Generated by Django 4.2.4 on 2023-10-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_ingredients_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='category',
            field=models.CharField(choices=[('soups', 'Soups'), ('salad', 'Salads'), ('seafood', 'Sea Food'), ('desserts', 'Desserts'), ('fast_food', 'Fast Food'), ('meat', 'Meat')], max_length=10, null=True),
        ),
    ]
