# Generated by Django 4.2.5 on 2023-10-07 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0012_remove_ingredients_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='category',
            field=models.CharField(choices=[('soups', 'Soups'), ('salad', 'Salads'), ('seafood', 'Sea Food'), ('desserts', 'Desserts'), ('fast_food', 'Fast Food'), ('meat', 'Meat')], max_length=10, null=True),
        ),
    ]
