# Generated by Django 4.2.5 on 2023-09-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('comment_count', models.IntegerField(null=True, verbose_name='comment count')),
                ('rating', models.FloatField(null=True, verbose_name='rating')),
                ('ingredients', models.CharField(max_length=1024, null=True, verbose_name='ingredients')),
                ('instructions', models.CharField(max_length=2048, null=True, verbose_name='instructions')),
                ('category', models.CharField(max_length=255, null=True, verbose_name='category')),
                ('favorites_count', models.IntegerField(null=True, verbose_name='favorites count')),
                ('duration_time', models.IntegerField(null=True, verbose_name='duration time')),
            ],
        ),
    ]
