# Generated by Django 4.2.5 on 2023-09-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtering_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='TestRecipes',
        ),
    ]
