# Generated by Django 4.2.5 on 2023-10-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='a',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
