# Generated by Django 4.2.5 on 2023-10-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_airecipes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airecipes',
            old_name='text',
            new_name='message',
        ),
    ]
