# Generated by Django 4.2.5 on 2023-10-24 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_image_airecipes_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airecipes',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='airecipes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 24, 13, 56, 10, 24480, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
