# Generated by Django 4.2.5 on 2023-10-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_user_airecipes_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airecipes',
            old_name='image_url',
            new_name='image_field',
        ),
    ]
