# Generated by Django 4.2.5 on 2023-11-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_airecipes_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airecipes',
            old_name='image_field',
            new_name='image',
        ),
    ]
