# Generated by Django 4.2.4 on 2023-09-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_passwordresetcode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
