# Generated by Django 4.2.4 on 2023-09-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20230928_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
