# Generated by Django 4.2.5 on 2023-10-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(default='static/avatars/no_picture.png', upload_to='avatars'),
        ),
    ]
