# Generated by Django 4.2.4 on 2023-09-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtering_test', '0002_rename_recipes_testrecipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecipes',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='testrecipes',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testrecipes',
            name='duration_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testrecipes',
            name='favorites_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='testrecipes',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testrecipes',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testrecipes',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='testrecipes',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
